ALTER TABLE MENUS_USUARIO
   ADD CONSTRAINT FK_MEN_USU_COD_NIV_1 FOREIGN KEY (COD_NIVEL_1_FK) REFERENCES MENU(ID_MENU),
   ADD CONSTRAINT FK_MEN_USU_COD_NIV_2 FOREIGN KEY (COD_NIVEL_2_FK) REFERENCES SUBMENU_NIVEL_1(ID_SUBMENU_NIVEL_1);
   
   
   ALTER TABLE MENUS_USUARIO
   ADD CONSTRAINT FK_MEN_USU_COD_NIV_1 FOREIGN KEY (COD_NIVEL_1_FK) REFERENCES MENU(ID_MENU)
   ADD  CONSTRAINT FK_MEN_USU_COD_NIV_2 FOREIGN KEY (COD_NIVEL_2_FK) REFERENCES SUBMENU(ID_SUBMENU);
   
   ALTER TABLE SUBMENU_NIVEL_1
   ADD CONSTRAINT FK_SUBMENU_NIV1_ID_MENU FOREIGN KEY(ID_MENU_FK) REFERENCES MENU(ID_MENU);
   
   
   ALTER TABLE AVISO
   ADD CONSTRAINT FK_AVISO_COD_FREC_REPET FOREIGN KEY(COD_FREC_REPETICION_FK) REFERENCES TPO_FRECU_REPETICION(ID_FRECU_REPETICION);
   
 
   ALTER TABLE PROYECTO_FACTURACION_MES
   ADD CONSTRAINT FK_AVISO_ID_PROYECTO FOREIGN KEY(ID_PROYECTO_FK) REFERENCES PROYECTO(ID_PROYECTO);
   
   SELECT mu from com.myfactory.SBootWebProject.model.MenusUsuario mu  JOIN  mu.menu me JOIN  mu.user us WHERE us.id = :idUsuario AND   me.idmenu > 0