CREATE TABLE PROYECTO_FACTURACION_MES (
  ID_PROYECTO_FAC_MES INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ID_PROYECTO_FK INT NOT NULL,
  NUM_MES INT NOT NULL,
  NUM_ANYO INT NOT NULL,
  FEC_GENERACION DATE NOT NULL,
  COD_ESTADO TINYINT NOT NULL
);

ALTER TABLE PROYECTO_FACTURACION_MES
   ADD CONSTRAINT FK_AVISO_ID_PROYECTO FOREIGN KEY(ID_PROYECTO_FK) REFERENCES PROYECTO(ID_PROYECTO);